#' Example data for iProPath
#'
#' A small example dataset used in README and examples.
#'
#' @format A list with elements:
#' \describe{
#'   \item{mediator_list}{List of mediator data objects.}
#'   \item{x_df_list}{List of X data frames/matrices.}
#'   \item{Y_list}{List of outcome matrices.}
#'   \item{fixed_cov}{NULL in this example.}
#'   \item{y_covdf_list}{NULL in this example.}
#' }
#' @source Generated by the iProPath pipeline (demo subset).
"sample_data"
